In [359]:
import numpy as np

class Dimensional:
    def __init__( self, dimensions_ = 3, initialValues = None, matrixMultiplication_ = False ):
        self.dimensions = dimensions_
        self.matrixMultiplication = matrixMultiplication_
        if initialValues != None:
            self.components = initialValues
        else:
            self.components = np.array( [ 0 ] * self.dimensions, np.float )
    def SquareMagnitude( self ):
        return ( self.components * self.components ).sum()
    def Magnitude( self ):
        return np.sqrt( self.SquareMagnitude() )
    def DotProduct( self, other ):
        if other.dimensions == self.dimensions:
            return ( other.components * self.components ).sum()
        return None
    def AngleBetween( self, other ):
        return np.arccos( np.divide( self.DotProduct( other ), np.multiply( other.Magnitude(), self.Magnitude() ) ) )
    def CrossDeterminant( self, other ):
        if other.dimensions == self.dimensions and ( self.dimensions == 7 or self.dimensions == 3 ):
            return np.linalg.det( np.array( [ np.array( [ 1 ] * self.dimensions, np.float ), self.components, other.components ] ) )
    def CrossProduct( self, other ):
        if other.dimensions == self.dimensions and ( self.dimensions == 7 or self.dimensions == 3 ):
            newVector = np.array( [ np.float( 0 ) ] * self.dimensions, np.float )
            sign = np.float( -1 )
            for i in range( 0, self.dimensions ):
                iInitialized = False
                for j in range( 0, self.dimensions ):
                    for k in range( 0, other.dimensions ):
                        #print( "if " + str( j ) + " != " + str( k ) + " and (" + str( j ) + " != " + str( i ) + " and " + str( k ) + " != " + str( i ) + " )" )
                        if j != k and j != i and k != i:
                            #print( ( str( newVector[ i ] ) + ", " ) + str( self.components[ j ] * other.components[ k ] ) )
                            if iInitialized == False:
                                newVector[ i ] = self.components[ j ] * other.components[ k ] * sign
                                iInitialized = True
                            else:
                                newVector[ i ] -= self.components[ j ] * other.components[ k ] * sign
                                if sign < 0:
                                    sign = np.float( 1 )
                                else:
                                    sign = np.float( -1 )
            return newVector
        return None
    def __mul__( self, other ):
        if type( other ) is Dimensional:
            if self.matrixMultiplication == True:
                return np.multiply( self.components, other.components )
            return self.DotProduct( other )
        else:
            np.multiply( self.components, other )
    def __div__( self, other ):
        return np.divide( self.components, other )
    def __add__( self, other ):
        return np.add( other )
    def __sub__( self, other ):
        return np.sub( other )
    def __imul__( self, other ):
        self.components = ( self * other )
        return self.components
    def __idiv__( self, other ):
        self.components = ( self / other )
        return self.components
    def __iadd__( self, other ):
        self.components = ( self + other )
        return self.components
    def __isub__( self, other ):
        self.components = ( self - other )
        return self.components
    def __neg__( self ):
        return -self.components
    def __pos__( self ):
        return np.abs( self.components )
    
Vector = Dimensional

In [348]:
v = Dimensional()
v.components

array([0., 0., 0.])

In [349]:
v.components[ 0 ] = np.float( 1 )
v.components[ 1 ] = np.float( 2 )
v.components[ 2 ] = np.float( 3 )
v.Magnitude()

3.7416573867739413

In [350]:
v.components

array([1., 2., 3.])

In [351]:
b = Dimensional()

In [352]:
b.components[ 0 ] = np.float( 4 )
b.components[ 1 ] = np.float( 5 )
b.components[ 2 ] = np.float( 6 )
b.Magnitude()

8.774964387392123

In [353]:
v.DotProduct( b )

32.0

In [354]:
b.components

array([4., 5., 6.])

In [355]:
v.components

array([1., 2., 3.])

In [356]:
v.AngleBetween( b )

0.2257261285527342

In [357]:
b.CrossProduct( v )

array([-3.,  6., -3.])

In [358]:
np.linalg.det( np.array( [ np.array( [ 1 ] * 3, np.float ), v.components, b.components ] ) )

0.0